apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: voting-app
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 3000
    targetPort: 3000
  selector:
    app: result
