apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: voting-app
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 3000
    targetPort: 3000
  selector:
    app: vote
  
